# fly.toml file generated for curso-django on 2023-01-31T01:45:48-03:00

app = "curso-django"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[env]
  EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
  PORT = "8000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true


[deploy]
  command = "./start.sh"  # Aqui você especifica o comando de inicialização do aplicativo

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"



# [[statics]]
#  guest_path = "/app/public"
#  url_prefix = "/static/"

