# Generated by Django 4.1.2 on 2022-10-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_modulo_slug'),
    ]

    operations = [
    ]
